// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDelete() {
  return window['go']['main']['App']['ConfirmDelete']();
}

export function GetJsonData() {
  return window['go']['main']['App']['GetJsonData']();
}

export function SaveJsonData(arg1) {
  return window['go']['main']['App']['SaveJsonData'](arg1);
}

export function SetJsonData(arg1) {
  return window['go']['main']['App']['SetJsonData'](arg1);
}
