// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDelete():Promise<boolean>;

export function GetJsonData():Promise<string>;

export function SaveJsonData(arg1:string):Promise<Error>;

export function SetJsonData(arg1:string):Promise<void>;
